# typed: false
# frozen_string_literal: true

# Homebrew formula for pub CLI
# This formula is auto-generated by GoReleaser on releases.
# Manual changes will be overwritten.
#
# To install: brew install jonandersen/tap/pub
# Or first tap: brew tap jonandersen/tap && brew install pub

class Pub < Formula
  desc "CLI for the Public.com trading API"
  homepage "https://github.com/jonandersen/public-cli"
  license "MIT"

  # GoReleaser will update these values automatically
  # For manual testing, update version, url, and sha256

  on_macos do
    on_intel do
      url "https://github.com/jonandersen/public-cli/releases/download/v#{version}/pub_#{version}_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_AMD64"
    end

    on_arm do
      url "https://github.com/jonandersen/public-cli/releases/download/v#{version}/pub_#{version}_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jonandersen/public-cli/releases/download/v#{version}/pub_#{version}_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"
    end

    on_arm do
      url "https://github.com/jonandersen/public-cli/releases/download/v#{version}/pub_#{version}_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
    end
  end

  def install
    bin.install "pub"
  end

  test do
    system "#{bin}/pub", "version"
  end
end
